stages:
  - unittest
  - functest

py27:
  image: python:2.7
  stage: unittest
  script:
    - pip install .
    - python tests.py TestUnit

py35:
  image: python:3.5
  stage: unittest
  script:
    - pip install .
    - python tests.py TestUnit
